config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: %i[index edit update]
  resources :groups, only: %i[new create edit update] do
    resources :messages, only: %i[index create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_message = @messages.where'id > ?', params[:id] }
    end
  end

  private
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth, if: :production?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]
  def index

  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました。'
    else
      render :new
    end
  end

  def edit
    @other_members = @group.users.where.not(id: current_user.id)
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group),notice: 'グループを編集しました'
    else
      render :edit
    end
  end

private

  def group_params
    params.require(:group).permit(:name, { user_ids: []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li
            = message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__field__label', for: "chat_group_#{group.name}"
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__field__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__field__label', for: "chat_group_#{group.id}"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__field__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__field__label', for: "chat_group_チャットメンバー"
    .chat-group-form__field--right
      .chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member{id: current_user.id}
          %input{ name: "group[user_ids][]", type: "hidden", value: current_user.id ,id: "group_user_ids"}/
          %p.chat-group-user__name
            = current_user.name
        - if @other_members.present?
          = render partial: "other_members", collection: @other_members, as: "other_member"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_other_members.html.haml
.chat-group-user.clearfix.js-chat-member{id: "#{other_member.id}"}
  %input#group_user_ids{name: "group[user_ids][]", type: "hidden", value: "#{other_member.id}"}/
  %p.chat-group-user__name
    = other_member.name
  %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'shared/chat-side'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_form.html.haml
= form_for [@group, @message],html: {id: "create_message"} do |f|
  = f.text_field :content, class: 'new_message__input-box__text', placeholder: 'type a message'
  .new_message__input-box
    = f.label :image, class: 'new_message__input-box__image-label' do
      = fa_icon 'picture-o'
      = f.file_field :image, class: 'new_message__input-box__image-label__input'
  = f.submit 'Send', class: 'new_message__submit-btn'

app/views/messages/_message.html.haml
.message{"data-message_id": message.id}
  .message__upper-info
    %p.message__upper-info__user
      = message.user.name
    %p.message__upper-info__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  %p.message__text
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'form__mask__image' if message.image.present?

app/views/messages/index.html.haml
.flash-box
.wrapper
  = render 'shared/chat-side'
  .chat-main
    .main-header
      .main-header__current-group{group_id: @group.id}
        %h2.current-group__name
          = @group.name
        %ul.member-list
          Member：
          - @group.users.each do |user|
            %li.member-list__member
              = user.name
      = link_to "Edit", "edit", class: "main-header__edit-btn"
    .messages
      = render @messages
    .form
      = render 'form'

app/views/shared/_chat-side.html.haml
.chat-side
  .chat-side__side-header
    %p.chat-side__side-header__user-name
      = current_user.name
    %ul.chat-side__side-header__user-menu
      %li.user-menu__edit-user
        = link_to new_group_path, class: "white-text" do
          = fa_icon 'pencil-square-o'
      %li.user-menu__new-group
        = link_to edit_user_path(current_user), class: "white-text" do
          = fa_icon 'cog'
  .chat-side__groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group), class: "white-text" do
          %p.group__group-name
            = group.name
          %p.group__latest-message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'